
bitmaps["hive"] := Map()
bitmaps["hive"]["day"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day"]), Gdip_GraphicsClear(G, 0xffd28f0c), Gdip_DeleteGraphics(G)
bitmaps["hive"]["night"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["night"]), Gdip_GraphicsClear(G, 0xffc08200), Gdip_DeleteGraphics(G)
bitmaps["hive"]["day-altUI"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day-altUI"]), Gdip_GraphicsClear(G, 0xff916507), Gdip_DeleteGraphics(G)
bitmaps["hive"]["night-altUI"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["night-altUI"]), Gdip_GraphicsClear(G, 0xff845c00), Gdip_DeleteGraphics(G)
bitmaps["hive"]["day-gifted"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day-gifted"]), Gdip_GraphicsClear(G, 0xffb97e03), Gdip_DeleteGraphics(G)
bitmaps["hive"]["night-gifted"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["night-gifted"]), Gdip_GraphicsClear(G, 0xffaa7400), Gdip_DeleteGraphics(G)
bitmaps["hive"]["noshadow-day"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["noshadow-day"]), Gdip_GraphicsClear(G, 0xffffb325), Gdip_DeleteGraphics(G)
bitmaps["hive"]["noshadow-night"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["noshadow-night"]), Gdip_GraphicsClear(G, 0xff694a00), Gdip_DeleteGraphics(G)
bitmaps["hive"]["noshadow-gifted"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["noshadow-gifted"]), Gdip_GraphicsClear(G, 0xffe39d1f), Gdip_DeleteGraphics(G)
bitmaps["hive"]["wing"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["wing"]), Gdip_GraphicsClear(G, 0xffa28645), Gdip_DeleteGraphics(G)

; night honey/meteor currently missing. snow(storm) currently not possible until beesmas.
bitmaps["spawn"] := Map()
bitmaps["spawn"]["day"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day"]), Gdip_GraphicsClear(G, 0xff937B1F), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["night"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night"]), Gdip_GraphicsClear(G, 0xff796615), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["day-honey"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day-honey"]), Gdip_GraphicsClear(G, 0xffC1AE55), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["night-honey"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night-honey"]), Gdip_GraphicsClear(G, 0xff000000), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["day-meteor"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day-meteor"]), Gdip_GraphicsClear(G, 0xff957A70), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["night-meteor"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night-meteor"]), Gdip_GraphicsClear(G, 0xff000000), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["day-snow"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day-snow"]), Gdip_GraphicsClear(G, 0xff000000), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["night-snow"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night-snow"]), Gdip_GraphicsClear(G, 0xff000000), Gdip_DeleteGraphics(G)
